app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself', validators=[Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
    title = StringField("Caption",validators=[Required()])
    body = TextAreaField("Whats on your mind?", validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    name = StringField("Your Name")
    comment_body = StringField("Comment",validators=[Required()])
    submit = SubmitField('Submit')

class SubscribeForm(FlaskForm):
    name = StringField("Your Name")
    email = StringField("Email")
    submit= SubmitField('Subscribe')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos = UploadSet('photos',IMAGES)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)        
    # creating app configurations
    app.config.from_object(config_options[config_name])
    #initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    #registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    #will add the views and forms
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from flask_login import login_required,current_user
from ..models import User,Blog,Comment,Subscribe
from .forms import UpdateProfile,BlogForm,CommentForm,SubscribeForm
from .. import db,photos
from ..email import mail_message

@main.route('/')
def index():
    '''
        View root page function that returns the index page and its data
    '''
    poems = Blog.query.all()
    comments = Comment.query.all()
    title = 'POETRY HOME | Home of Poetry'

    return render_template('index.html',comments=comments,poems=poems,title=title)

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    title = "My Profile"

    return render_template("profile/profile.html",title=title,user=user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/blog/new',methods=['GET','POST'])
@login_required
def new_blog():
    form = BlogForm()
    subscriber= Subscribe.query.all()
    if form.validate_on_submit():
        title=form.title.data
        body=form.body.data
        new_blog=Blog(title=title,body=body,user=current_user)
        new_blog.save_blog()
        for sub in subscriber:
            mail_message("New Blog Alert","email/update",sub.email,sub=sub)
        return redirect(url_for('main.index'))

    title = 'Home of poetry'
    return render_template('new_blog.html',title=title,blog_form=form)
    
@main.route('/blog/<int:id>')
def view_blog(id):
    form=BlogForm()
    user=User.query.filter_by(id=id).first()
    blog= Blog.query.filter_by(id=id).first()

    comments = Comment.get_comments(id)


    title = 'Home of Poetry'
    return render_template('blog.html',comments=comments,title=title,blog=blog,blog_form=form,user=user)


@main.route('/about')
def about():
    title = 'Home Of Poetry'
    return render_template('about.html',title=title)

@main.route('/comment/new/<int:id>',methods=['GET','POST'])
def new_comment(id):
    blog=Blog.query.filter_by(id=id).first()

    if blog is None:
        abort(404)
    form = CommentForm()

    if form.validate_on_submit():
        name = form.name.data
        comment_body = form.comment_body.data
        new_comment = Comment(comment_body=comment_body,name=name,blog=blog)
        new_comment.save_comment()
        return redirect(url_for('main.view_blog',id=blog.id))

    title='Comment'
    return render_template('new_comment.html',title=title,comment_form=form)

@main.route('/subscribe',methods=["GET","POST"])
def subscribe():
    form=SubscribeForm()

    if form.validate_on_submit():
        subscriber = Subscribe(name=form.name.data,email=form.email.data)
        db.session.add(subscriber)
        db.session.commit()

        mail_message("Welcome to Home of Poetry","email/subscribe_user",subscriber.email,subscriber=subscriber)
        flash('A confirmation by email has been sent to you by email')
        return redirect(url_for('main.index'))
        title = 'Subscribe'
    return render_template('subscribe.html',subscribe_form=form)

app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container jumbotron">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <img src="./static/photos/coverpic.jpg" class="cover"/>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Poetry is the medicine to the soul</h4>
            </div>
            <div class="panel-body">
                    <p>Do you ever wake up in the middle of the night to right something?</p>
                    <p>Do you ever feel like opening up somewhere without anyone to judge?</p>
                    <p>Well thats how I started my poetry journey</p>
                    <p>Everyone needs a friend and having somewhere to write and rant about your issues could be the best place. 
                    Well, lets walk together in this journey and learn much much more.
                    </p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <i>Pure mathematics is, in its way, the poetry of logical ideas.</i>
            </div>
            <div class="panel-footer">
                <i>Albert Einstein</i>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <i>Poetry is when an emotion has found its thought and the thought has found words.</i>
            </div>
            <div class="panel-footer">
                <i> Robert Frost</i>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <i>Painting is silent poetry, and poetry is painting that speaks.</i>
            </div>
            <div class="panel-footer">
                <i>Plutarch</i>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
    </div>
    <div class="jumbotron" style="background-color:black; color:aliceblue; font-size:20px; ">
            <div class="row" style="padding-top:5%">
                    <div class="col-md-2 col-lg-2"></div>
                    <div class="col-md-4 col-lg-4">
                        <p>&copy; Copyright 2018 <a href="VickyMutai@github.com">Victoria Mutai</a></p>  
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <p>Contact me at: <a href="mailto:vicky.mutai@gmail.com">My Email</a></p>
                        <p>Phone Number: 0716889165</p>
                    </div>
                    <div class="col-md-2 col-lg-2"></div>    
                </div>
            </div>
</div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<head>
    {{moment.include_jquery()}}
    {{moment.include_moment()}}
</head>
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% include 'navbar.html' %}

app/templates/blog.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container">
    <h1>
        {{blog.title | upper}}
    </h1>
    <br><br>
    <p>Author: <i>{{blog.user.username}}</i></p>
    <p>{{blog.body}}</p>
    <div class="row">
        <div class="col-md-3">
            <p><a href="/comment/new/{{blog.id}}" class="btn btn-info">Write Comment</a></p>
        </div>
        <div class="col-md-9">
                <button data-toggle="collapse" data-target="#comment" class="btn btn-info">View Comments</button>
                <div id="comment" class="collapse">
                    {{ macro.displayComments(comments) }}
                </div>  
        </div>
    </div>
</div>
        
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}
{% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container">    
        <div class="row">
                  <img src="./static/photos/coverpic.jpg" class="cover" style="width:100%"/>
            </div>
        
    <div class="row col-sm-9 col-xs-9 col-md-8 col-lg-8">
            <h2>THOUGHTS</h2>
            <p>Its well past midnight, thoughts after thoughts haunt my heart</p>
            <p>Was it the best solution?</p>
            <p>Leting go was not my favorite part of it all</p>
            <p>It all comes down to the reason!</p>
            <br><br>
            <p>Maybe someday the reasons will be clear</p>
            <p>Maybe someday I will understand</p>
            <p>Maybe someday this will get better</p>
            <p>Maybe someday things will change</p>
            <p>Maybe just maybe....</p>
            <br><br>
            <p>Did you see how happy they were?</p>
            <p>Did you hear them whisper?</p>
            <p>I hoped that you would come to my rescue</p>
            <p>I didnt believe you</p>
            <p>But I still placed my hope on you</p>
            <br>
            <p><b>To be continued.....</b></p>
            </div>
    <div class="row col-sm-1 col-xs-1 col-md-1 col-lg-1" ></div>
    <div class="row col-sm-2 col-xs-2 col-md-3 col-lg-3" style="border-left: 3px black">
        <div class="button btn btn-info">
            <a href="/subscribe">Subscribe Here</a>
        </div>
            <h2>View Blogs</h2>
                {{macro.displayBlog(poems)}}
        </div>
    </div>
    <div class="footer" style="background-color:black; color:aliceblue; font-size:20px;">
            <div class="row" style="padding-top:5%">
                    <div class="col-md-2 col-lg-2"></div>
                    <div class="col-md-4 col-lg-4">
                        <p>&copy; Copyright 2018 <a href="VickyMutai@github.com">Victoria Mutai</a></p>  
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <p>Contact me at: <a href="mailto:vicky.mutai@gmail.com">My Email</a></p>
                        <p>Phone Number: 0716889165</p>
                    </div>
                    <div class="col-md-2 col-lg-2"></div>    
                </div>
            </div>
{% endblock %}

app/templates/macros.html
<!--display blog in macros-->
{% macro displayBlog(blog_list) %}
    {% for blog in blog_list %}
        <h3><a href="/blog/{{blog.id}}">{{blog.title}}</a></h3>
        <p>Posted on: {{blog.timestamp}}</p>
    {% endfor %}
{% endmacro %}

{% macro displayComments(comment_list) %}
{% for comment in comment_list %}
<div class="row col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <p>Author name: <i>{{ comment.name }}</i></p> 
        </div>
        <div class="panel-body">
            <p>{{ comment.comment_body}}</p>
        </div>
        <div class="panel-footer">
            <i>{{comment.timestamp}}</i>
        </div>
    </div>
</div>
            
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> BLOG </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About Me</a></li>
                <li><a href="/blog/new">Write Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {%endif%}
              </ul>
        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            {{ wtf.quick_form(blog_form) }}
        </div>
        <div class="col-md-2"></div>

    </div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-comment">
            
                {{ wtf.quick_form(comment_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Displaying profile photo -->
        <div class="col-md-4">
            <h3>{{user.username | capitalize}}</h3>
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        
                {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
        
              <input type="file"  name="photo" class="form-control" required>
              <input type="submit">
              {% endif %}
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <!--Displaying user bio-->
            {% if user.bio %}
            <p>{{user.bio}}</p>
            {% else %}
            <p>{{user.username| capitalize}} has no bio</p>
            {% endif %}

            {% if user==current_user %}
                <a class="btn btn-info" href="{{url_for('main.update_profile',uname=user.username)}}">Edit Profile</a>
            {% endif %}
            </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
    {{wtf.quick_form(form)}}
{% endblock %}

app/templates/subscribe.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-comment">
            
                {{ wtf.quick_form(subscribe_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}